clone:
  git:
    image: woodpeckerci/plugin-git

when:
  branch: dev-pages
  event: [push]

steps:
  build:
    image: node:lts-alpine
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm run build

  publish:
    image: alpine/git
    environment:
      BUILD_OUTPUT: dist
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - cp -ar $BUILD_OUTPUT/. $CI_REPO_NAME/
      - cp .domains $CI_REPO_NAME || true
      - cd $CI_REPO_NAME
      - git add .
      - 'if ! git diff --cached --quiet; then git commit -m "chore(deploy): Woodpecker CI ${CI_BUILD_CREATED} update pages [SKIP CI]" && git push; fi'
