[package]
name = "sanctum"
version = "0.1.0"
edition = "2024"
build = "build.rs"
authors = ["Kyronix"]
license = "AGPL-3.0-or-later"
description = "Your personal financial fortress. Private. Encrypted. Local-first."
repository = "https://codeberg.org/Kyronix/Sanctum"
homepage = "https://codeberg.org/Kyronix/Sanctum"
readme = "README.md"
keywords = ["finance", "privacy", "crypto", "slint", "sqlite"]
categories = ["cryptography", "database"]
exclude = [
    ".img/*",
    ".envrc"
]

[[bin]]
name = "sanctum"
path = "src/main.rs"

[dependencies]
slint = { version = "1.14.1", features = ["renderer-winit-skia"] }
tokio = { version = "1.48.0", features = ["full"] }
rusqlite = { version = "0.38.0", features = ["bundled-sqlcipher"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
toml = "0.9.10"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
chrono = { version = "0.4.42", features = ["serde"] }
secrecy = "0.10.3"
thiserror = "2.0.17"
log = "0.4.29"
env_logger = "0.11.8"
directories = "6.0.0"
reqwest = { version = "0.12.28", features = ["json", "stream", "socks"] }
futures = "0.3.31"
regex = "1.12.2"
rand = "0.9.2"
rfd = "0.15"
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend", "area_series", "line_series"] }
fontdb = "0.23.0"
usvg = "0.45.1"
fluent-bundle = "0.16"
fluent-syntax = "0.11"
sys-locale = "0.3"
unic-langid = "0.9"

[build-dependencies]
slint-build = "1.14.1"
